name: Publish BlazorSlice.Toast to NuGet

on: [push]
    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'BlazorSlice.Toast.sln'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
      
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.6
      with:
          versionSpec: '5.x'
          
    - name: Use GitVersion
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v0.9.6
      
    - run: |
        echo "NuGetVersionV2: ${{ steps.gitversion.outputs.nuGetVersionV2 }}"
        echo "NuGetPreReleaseTagV2: ${{ steps.gitversion.outputs.CommitsSinceVersionSourcePadded }}"

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Build
      run: dotnet build BlazorSlice.Toast/BlazorSlice.Toast.csproj --configuration Release
      
    - name: Pack with dotnet
      run: dotnet pack BlazorSlice.Toast/BlazorSlice.Toast.csproj --output nuget-packages --configuration Release -p:PackageVersion=${{ steps.gitversion.outputs.nuGetVersionV2 }}    
    - name: Publish
      run: dotnet nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
