name: Publish BlazorSlice.Toast to NuGet

on: 
    workflow_dispatch:
        inputs:
            nuget-version:
                description: 'Nuget Version v[0-9]+.[0-9]+.[0-9]+*'
                required: true
                default: ''
                type: string
    push:
        tags:
        - "v[0-9]+.[0-9]+.[0-9]+*"
    
    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'BlazorSlice.Toast.sln'
      VERSION: 1.0.0

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Set version from input
      if: ${{ github.event.inputs.nuget-version != '' }} 
      env:
        TAG: ${{ github.event.inputs.nuget-version }}
      run: echo "VERSION=${TAG#v}" >> $GITHUB_ENV
      
    - name: Set version variable from tag
      if: ${{ github.ref_type == 'tag' }}
      env:
        TAG: ${{ github.ref_name }}
      run: echo "VERSION=${TAG#v}" >> $GITHUB_ENV

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Build
      run: dotnet build BlazorSlice.Toast/BlazorSlice.Toast.csproj --configuration Release
      
    - name: Pack with dotnet
      run: dotnet pack BlazorSlice.Toast/BlazorSlice.Toast.csproj --output nuget-packages --configuration Release -p:PackageVersion=$VERSION    
      
    - name: Publish
      if: (github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')) || startsWith(${{ github.event.inputs.nuget-version }}, 'v')
      run: dotnet nuget push **\*.nupkg --source 'https://api.nuget.org/v3/index.json' --api-key ${{secrets.NUGET_API_KEY}}
